gems:
 - jekyll-textile-converter
name: Game AI North
description: Game AI North is 2 Days of Talks on Design, Systems, and Production - Copenhagen, October 17-18 2017
url: http://GameAINorth.com
permalink: pretty
redcloth:
  hard_breaks: false
organizers:
   - name: Emil "AngryAnt" Johansen
     twitter: AngryAnt
     image: emil.jpg
   - name: Charles Hinshaw
     twitter: nulldiver
     image: charles.jpg
   - name: Richard Kogelnig
     twitter: RichardKogelnig
     image: richard.jpg
   - name: Philip Dunstan
     twitter: phildunstan
     image: phil.jpg
